Hit escape to close search input
jaanauati/hyper-search pull request #10
Opened 2017-06-22 08:17 UTC by alex-cory

added ESCAPE to constants & added ESCAPE logic in `handleOnKeyDown`

2017-06-22 22:25 UTC, jaanauati requested changes

2017-06-22 22:25 UTC, jaanauati commented on src/containers.js
> +          if (this.toggleInput() === false) {
cool!,

I only have a little suggestion, this is processing the key-up event triggered by the visible input, so i believe you just can do:
```
  window.store.dispatch(toggleSearchInput(uid));
  if (this.props.term) this.props.term.focus();
```
makes sense or i just need more ☕️  :-)?

2017-06-23 21:52 UTC, jaanauati commented
turned out that i can push to your branch so I just made the change. Thanks!

2017-06-23 21:52 UTC, jaanauati approved these changes

2017-06-23 21:52 UTC, merged

2017-06-26 21:51 UTC, alex-cory commented on src/containers.js
> +          if (this.toggleInput() === false) {
Sounds good! Sorry was on a trip and just saw this. Looks good to me! :)