Add style, use foreground & background colors
jaanauati/hyper-search pull request #24
Opened 2018-03-01 20:29 UTC by willrstern

addresses https://github.com/jaanauati/hyper-search/issues/15
- break out styles into their own file
- add extra style to enhance the look of search
- support user background/foreground colors
- change `term.scrollDisp` to `term.scrollLines`

With #000 background, #fff foreground
  
<img width="250" alt="screen shot 2018-03-01 at 2 22 08 pm" src="https://user-images.githubusercontent.com/1680215/36867909-48714976-1d5c-11e8-8fab-42b630243b71.png">

With #fff background, #000 foreground
<img width="231" alt="screen shot 2018-03-01 at 2 22 45 pm" src="https://user-images.githubusercontent.com/1680215/36867931-6224005c-1d5c-11e8-89b7-a16dc26c28c4.png">

2018-03-02 21:48 UTC, jaanauati requested changes

2018-03-02 21:48 UTC, jaanauati commented on src/containerStyles.js
> +    borderRadius: '10px',
please sort alphabetically

2018-03-02 21:48 UTC, jaanauati commented on src/containers.js
> +focussedSessionUid: state.sessions.activeUid,
there are a lot of indentation changes, so this is showing a lot of changes in the code.  this makes things hard to review, can u please restore the file the to original state and only push the desired changes?
looking forward for your new code-changes, those screenshots look great!
thanks

2018-03-05 22:34 UTC, willrstern commented
@jaanauati Sorry about that.  I think my editor tried to format tabs to spaces or something like that...here you go.

2018-03-05 22:35 UTC, willrstern commented on src/containers.js
> +      term.scrollLines(_startRow - term.buffer.ydisp);
I noticed there was no `term.scrollDisp` command?  I'm not sure if they changed it or not.  It was only scrolling back and forth between the first and last results.

Changing this to `scrollLines` made things work.

2018-03-11 19:56 UTC, merged

2018-03-11 20:05 UTC, jaanauati commented
this looks great.... merged and published (v0.0.9).

Thanks!.