User Configureable Styles
jaanauati/hyper-search pull request #54
Opened 2019-04-27 16:52 UTC by aaronmarkey

Thought it would be cool to allow users to easily update some simple styling elements of hyper-search to better fit their Hyper setup. 

* Allows users to modify the border radius of buttons, and the input field.
* Allows users to modify margin between buttons.
* Allows users to change prev/next button text (undocumented in README.)

2019-04-27 22:31 UTC, jaanauati requested changes

2019-04-27 22:31 UTC, jaanauati commented on src/containerStyles.js
> +    nextButton: '▶',
could u please add a little description about these two to the readme file? (prev and nextButton, )

2019-04-27 22:31 UTC, jaanauati commented on README.md
> +
Can u please add your name to the Contributors section? (this same file, line 81, names are listed alphabetically).

2019-04-27 22:41 UTC, jaanauati commented
This looks good!, I tested the changes in my local and everything works well, regarding my two requests, I'd like you to make the tweaks so the screenshots use the same styles (I have a different styling setup), but please, let me know in case that u don't have time (I could merge this and deal w the docs later).

Thank you!

2019-04-28 00:02 UTC, aaronmarkey commented
Updated the README with your requests. I wasn't able to accurately replicate your setup locally, so the screens are still using mine.

2019-04-28 16:11 UTC, merged

2019-04-28 16:16 UTC, jaanauati commented
Your screenshots are perfect, hyper-search@0.2.0 has been pushed to npm.

Thank you!